# Generated by Django 2.2.5 on 2019-11-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_title', models.CharField(max_length=200)),
                ('first_level_hits', models.CharField(max_length=100)),
                ('hits_after_first', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='race_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_title', models.CharField(max_length=100)),
                ('ability_score_modifier', models.CharField(max_length=100)),
            ],
        ),
    ]
